# Generated by Django 3.0.5 on 2020-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='objet',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
