# Generated by Django 3.0.5 on 2020-04-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('info', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
